# Global Hurricane Tracks (IBTrACS)
## Description
The historical positions and intensities along the tracks of global tropical cyclones (TC) are provided
by NOAA's International Best Track Archive for Climate Stewardship (IBTrACS). Tropical Cyclones
are known as hurricanes in the north Atlantic and northeast Pacic ocean basins, typhoons in the
northwest Pacic ocean basin, cyclones in the north and south Indian Ocean basins, and tropical
cyclones in the southwest Pacic ocean basin. TCs endanger millions annually in those coastal
regions. IBTrACS collects data about TCs reported by international monitoring centers who have a
responsibility to forecast and report on TCs (and also includes some important historical datasets).
Presently, IBTrACS includes data from 9 dierent countries. Historically, the data describing these
systems has included best estimates of their track and intensity (hence the term, best track).
## Dataset
https://console.cloud.google.com/marketplace/details/noaa-public/hurricanes?filter=solution-type%3Adataset&filter=category%3Aclimate&q=public%20data&id=fa502e93-02a3-4606-8918-5d44a5e8f8f0
## Further Reading
How to process weather satellite data in real-time in BigQuery: 
https://cloud.google.com/blog/products/gcp/how-to-process-weather-satellite-data-in-real-time-in-bigquery
### Participant
Yifu Chen, team University of British Columbia

In [ ]:
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from IPython.display import Image

In [ ]:
drive.mount('/content/drive')
# left sidebar can easily browse through files and right click to "Copy path"
root_path = '/content/drive/My Drive/ProjectX/hurricane/'
df = pd.read_csv(root_path + "data-projectX_hurricane.csv")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (3,58) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
# set the display options to prevent truncating
pd.options.display.max_seq_items = 2000

In [ ]:
df.head()

             sid  season  number  ... mlc_wind mlc_pressure usa_atcf_id
0  2018314S06091    2019       4  ...      NaN          NaN    SI042018
1  2019005N05174    2019       2  ...      NaN          NaN    WP012019
2  2018365S13140    2019       8  ...      NaN          NaN    SP082018
3  2019005N05174    2019       2  ...      NaN          NaN    WP012019
4  2019132S16159    2019      23  ...      NaN          NaN    SP272019

[5 rows x 151 columns]

In [ ]:
df.describe()

              season         number  ...      mlc_wind  mlc_pressure
count  692457.000000  692457.000000  ...  30331.000000    578.000000
mean     1960.379839      49.156719  ...     56.422241    972.911765
std        41.455549      34.159127  ...     21.140651     18.313584
min      1842.000000       1.000000  ...     20.000000    914.000000
25%      1934.000000      20.000000  ...     40.000000    959.250000
50%      1969.000000      44.000000  ...     52.000000    972.000000
75%      1993.000000      73.000000  ...     70.000000    985.000000
max      2020.000000     163.000000  ...    140.000000   1016.000000

[8 rows x 131 columns]

In [ ]:
df.columns

Index(['sid', 'season', 'number', 'basin', 'subbasin', 'name', 'iso_time',
       'nature', 'latitude', 'longitude', 'wmo_wind', 'wmo_pressure',
       'wmo_agency', 'track_type', 'dist2land', 'landfall', 'iflag',
       'usa_agency', 'usa_latitude', 'usa_longitude', 'usa_record',
       'usa_status', 'usa_wind', 'usa_pressure', 'usa_sshs', 'usa_r34_ne',
       'usa_r34_se', 'usa_r34_sw', 'usa_r34_nw', 'usa_r50_ne', 'usa_r50_se',
       'usa_r50_sw', 'usa_r50_nw', 'usa_r64_ne', 'usa_r64_se', 'usa_r64_sw',
       'usa_r64_nw', 'usa_poci', 'usa_roci', 'usa_rmw', 'usa_eye',
       'tokyo_latitude', 'tokyo_longitude', 'tokyo_grade', 'tokyo_wind',
       'tokyo_pressure', 'tokyo_r50_dir', 'tokyo_r50_longitude',
       'tokyo_r50_short', 'tokyo_r30_dir', 'tokyo_r30_long', 'tokyo_r30_short',
       'tokyo_land', 'cma_latitude', 'cma_longitude', 'cma_cat', 'cma_wind',
       'cma_pressure', 'hko_latitude', 'hko_longitude', 'hko_cat', 'hko_wind',
       'hko_pressure', 'newdelhi_latitude', 'newdelhi_longitude',
       'newdelhi_grade', 'newdelhi_wind', 'newdelhi_pressure', 'newdelhi_ci',
       'newdelhi_dp', 'newdelhi_poci', 'reunion_latitude', 'reunion_longitude',
       'reunion_type', 'reunion_wind', 'reunion_pressure', 'reunion_tnum',
       'reunion_ci', 'reunion_rmw', 'reunion_r34_ne', 'reunion_r34_se',
       'reunion_r34_sw', 'reunion_r34_nw', 'reunion_r50_ne', 'reunion_r50_se',
       'reunion_r50_sw', 'reunion_r50_nw', 'reunion_r64_ne', 'reunion_r64_se',
       'reunion_r64_sw', 'reunion_r64_nw', 'bom_latitude', 'bom_longitude',
       'bom_type', 'bom_wind', 'bom_pressure', 'bom_tnum', 'bom_ci', 'bom_rmw',
       'bom_r34_ne', 'bom_r34_se', 'bom_r34_sw', 'bom_r34_nw', 'bom_r50_ne',
       'bom_r50_se', 'bom_r50_sw', 'bom_r50_nw', 'bom_r64_ne', 'bom_r64_se',
       'bom_r64_sw', 'bom_r64_nw', 'bom_roci', 'bom_poci', 'bom_eye',
       'bom_pos_method', 'bom_pressure_method', 'wellington_latitude',
       'wellington_longitude', 'wellington_wind', 'wellington_pressure',
       'nadi_latitude', 'nadi_longitude', 'nadi_cat', 'nadi_wind',
       'nadi_pressure', 'ds824_latitude', 'ds824_longitude', 'ds824_stage',
       'ds824_wind', 'ds824_pressure', 'td9636_latitude', 'td9636_longitude',
       'td9636_stage', 'td9636_wind', 'td9636_pressure', 'td9635_latitude',
       'td9635_longitude', 'td9635_wind', 'td9635_pressure', 'td9635_roci',
       'neumann_latitude', 'neumann_longitude', 'neumann_class',
       'neumann_wind', 'neumann_pressure', 'mlc_latitude', 'mlc_longitude',
       'mlc_class', 'mlc_wind', 'mlc_pressure', 'usa_atcf_id'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692457 entries, 0 to 692456
Columns: 151 entries, sid to usa_atcf_id
dtypes: float64(128), int64(3), object(20)
memory usage: 797.7+ MB

In [ ]:
df.iloc[:, : 50].hist(layout=(10,5), figsize=(20,50), bins=20)

AttributeError: ignored

In [ ]:
# from IPython.display import Image
# Image(url='https://im4.ezgif.com/tmp/ezgif-4-7a133bb18259.gif')